import type { SearchableSelectOption } from '@/components/ui/searchable-select'

export const countryPhoneOptions: SearchableSelectOption[] = [
  { value: '+1', label: '🇺🇸 United States (+1)', searchText: 'us usa united states canada +1' },
  { value: '+1-ca', label: '🇨🇦 Canada (+1)', searchText: 'canada +1' },
  { value: '+7', label: '🇷🇺 Russia (+7)', searchText: 'russia +7' },
  { value: '+20', label: '🇪🇬 Egypt (+20)', searchText: 'egypt +20' },
  { value: '+27', label: '🇿🇦 South Africa (+27)', searchText: 'south africa +27' },
  { value: '+30', label: '🇬🇷 Greece (+30)', searchText: 'greece +30' },
  { value: '+31', label: '🇳🇱 Netherlands (+31)', searchText: 'netherlands +31' },
  { value: '+32', label: '🇧🇪 Belgium (+32)', searchText: 'belgium +32' },
  { value: '+33', label: '🇫🇷 France (+33)', searchText: 'france +33' },
  { value: '+34', label: '🇪🇸 Spain (+34)', searchText: 'spain +34' },
  { value: '+36', label: '🇭🇺 Hungary (+36)', searchText: 'hungary +36' },
  { value: '+39', label: '🇮🇹 Italy (+39)', searchText: 'italy +39' },
  { value: '+40', label: '🇷🇴 Romania (+40)', searchText: 'romania +40' },
  { value: '+41', label: '🇨🇭 Switzerland (+41)', searchText: 'switzerland +41' },
  { value: '+43', label: '🇦🇹 Austria (+43)', searchText: 'austria +43' },
  { value: '+44', label: '🇬🇧 United Kingdom (+44)', searchText: 'uk united kingdom britain england +44' },
  { value: '+45', label: '🇩🇰 Denmark (+45)', searchText: 'denmark +45' },
  { value: '+46', label: '🇸🇪 Sweden (+46)', searchText: 'sweden +46' },
  { value: '+47', label: '🇳🇴 Norway (+47)', searchText: 'norway +47' },
  { value: '+48', label: '🇵🇱 Poland (+48)', searchText: 'poland +48' },
  { value: '+49', label: '🇩🇪 Germany (+49)', searchText: 'germany +49' },
  { value: '+51', label: '🇵🇪 Peru (+51)', searchText: 'peru +51' },
  { value: '+52', label: '🇲🇽 Mexico (+52)', searchText: 'mexico +52' },
  { value: '+53', label: '🇨🇺 Cuba (+53)', searchText: 'cuba +53' },
  { value: '+54', label: '🇦🇷 Argentina (+54)', searchText: 'argentina +54' },
  { value: '+55', label: '🇧🇷 Brazil (+55)', searchText: 'brazil +55' },
  { value: '+56', label: '🇨🇱 Chile (+56)', searchText: 'chile +56' },
  { value: '+57', label: '🇨🇴 Colombia (+57)', searchText: 'colombia +57' },
  { value: '+58', label: '🇻🇪 Venezuela (+58)', searchText: 'venezuela +58' },
  { value: '+60', label: '🇲🇾 Malaysia (+60)', searchText: 'malaysia +60' },
  { value: '+61', label: '🇦🇺 Australia (+61)', searchText: 'australia +61' },
  { value: '+62', label: '🇮🇩 Indonesia (+62)', searchText: 'indonesia +62' },
  { value: '+63', label: '🇵🇭 Philippines (+63)', searchText: 'philippines +63' },
  { value: '+64', label: '🇳🇿 New Zealand (+64)', searchText: 'new zealand +64' },
  { value: '+65', label: '🇸🇬 Singapore (+65)', searchText: 'singapore +65' },
  { value: '+66', label: '🇹🇭 Thailand (+66)', searchText: 'thailand +66' },
  { value: '+81', label: '🇯🇵 Japan (+81)', searchText: 'japan +81' },
  { value: '+82', label: '🇰🇷 South Korea (+82)', searchText: 'korea south +82' },
  { value: '+84', label: '🇻🇳 Vietnam (+84)', searchText: 'vietnam +84' },
  { value: '+86', label: '🇨🇳 China (+86)', searchText: 'china +86' },
  { value: '+90', label: '🇹🇷 Turkey (+90)', searchText: 'turkey +90' },
  { value: '+91', label: '🇮🇳 India (+91)', searchText: 'india +91' },
  { value: '+92', label: '🇵🇰 Pakistan (+92)', searchText: 'pakistan +92' },
  { value: '+93', label: '🇦🇫 Afghanistan (+93)', searchText: 'afghanistan +93' },
  { value: '+94', label: '🇱🇰 Sri Lanka (+94)', searchText: 'sri lanka +94' },
  { value: '+95', label: '🇲🇲 Myanmar (+95)', searchText: 'myanmar +95' },
  { value: '+98', label: '🇮🇷 Iran (+98)', searchText: 'iran +98' },
  { value: '+211', label: '🇸🇸 South Sudan (+211)', searchText: 'south sudan +211' },
  { value: '+212', label: '🇲🇦 Morocco (+212)', searchText: 'morocco +212' },
  { value: '+213', label: '🇩🇿 Algeria (+213)', searchText: 'algeria +213' },
  { value: '+216', label: '🇹🇳 Tunisia (+216)', searchText: 'tunisia +216' },
  { value: '+218', label: '🇱🇾 Libya (+218)', searchText: 'libya +218' },
  { value: '+220', label: '🇬🇲 Gambia (+220)', searchText: 'gambia +220' },
  { value: '+221', label: '🇸🇳 Senegal (+221)', searchText: 'senegal +221' },
  { value: '+223', label: '🇲🇱 Mali (+223)', searchText: 'mali +223' },
  { value: '+224', label: '🇬🇳 Guinea (+224)', searchText: 'guinea +224' },
  { value: '+225', label: '🇨🇮 Ivory Coast (+225)', searchText: 'ivory coast cote d ivoire +225' },
  { value: '+226', label: '🇧🇫 Burkina Faso (+226)', searchText: 'burkina faso +226' },
  { value: '+227', label: '🇳🇪 Niger (+227)', searchText: 'niger +227' },
  { value: '+228', label: '🇹🇬 Togo (+228)', searchText: 'togo +228' },
  { value: '+229', label: '🇧🇯 Benin (+229)', searchText: 'benin +229' },
  { value: '+230', label: '🇲🇺 Mauritius (+230)', searchText: 'mauritius +230' },
  { value: '+231', label: '🇱🇷 Liberia (+231)', searchText: 'liberia +231' },
  { value: '+232', label: '🇸🇱 Sierra Leone (+232)', searchText: 'sierra leone +232' },
  { value: '+233', label: '🇬🇭 Ghana (+233)', searchText: 'ghana +233' },
  { value: '+234', label: '🇳🇬 Nigeria (+234)', searchText: 'nigeria +234' },
  { value: '+235', label: '🇹🇩 Chad (+235)', searchText: 'chad +235' },
  { value: '+236', label: '🇨🇫 Central African Republic (+236)', searchText: 'central african republic +236' },
  { value: '+237', label: '🇨🇲 Cameroon (+237)', searchText: 'cameroon +237' },
  { value: '+238', label: '🇨🇻 Cape Verde (+238)', searchText: 'cape verde +238' },
  { value: '+239', label: '🇸🇹 Sao Tome and Principe (+239)', searchText: 'sao tome principe +239' },
  { value: '+240', label: '🇬🇶 Equatorial Guinea (+240)', searchText: 'equatorial guinea +240' },
  { value: '+241', label: '🇬🇦 Gabon (+241)', searchText: 'gabon +241' },
  { value: '+242', label: '🇨🇬 Republic of the Congo (+242)', searchText: 'congo brazzaville republic of congo +242' },
  { value: '+243', label: '🇨🇩 DR Congo (+243)', searchText: 'dr congo kinshasa +243' },
  { value: '+244', label: '🇦🇴 Angola (+244)', searchText: 'angola +244' },
  { value: '+245', label: '🇬🇼 Guinea-Bissau (+245)', searchText: 'guinea-bissau +245' },
  { value: '+246', label: '🇮🇴 British Indian Ocean Territory (+246)', searchText: 'british indian ocean territory +246' },
  { value: '+248', label: '🇸🇨 Seychelles (+248)', searchText: 'seychelles +248' },
  { value: '+249', label: '🇸🇩 Sudan (+249)', searchText: 'sudan +249' },
  { value: '+250', label: '🇷🇼 Rwanda (+250)', searchText: 'rwanda +250' },
  { value: '+251', label: '🇪🇹 Ethiopia (+251)', searchText: 'ethiopia +251' },
  { value: '+252', label: '🇸🇴 Somalia (+252)', searchText: 'somalia +252' },
  { value: '+253', label: '🇩🇯 Djibouti (+253)', searchText: 'djibouti +253' },
  { value: '+254', label: '🇰🇪 Kenya (+254)', searchText: 'kenya +254' },
  { value: '+255', label: '🇹🇿 Tanzania (+255)', searchText: 'tanzania +255' },
  { value: '+256', label: '🇺🇬 Uganda (+256)', searchText: 'uganda +256' },
  { value: '+257', label: '🇧🇮 Burundi (+257)', searchText: 'burundi +257' },
  { value: '+258', label: '🇲🇿 Mozambique (+258)', searchText: 'mozambique +258' },
  { value: '+260', label: '🇿🇲 Zambia (+260)', searchText: 'zambia +260' },
  { value: '+261', label: '🇲🇬 Madagascar (+261)', searchText: 'madagascar +261' },
  { value: '+262', label: '🇷🇪 Reunion (+262)', searchText: 'reunion mayotte +262' },
  { value: '+263', label: '🇿🇼 Zimbabwe (+263)', searchText: 'zimbabwe +263' },
  { value: '+264', label: '🇳🇦 Namibia (+264)', searchText: 'namibia +264' },
  { value: '+265', label: '🇲🇼 Malawi (+265)', searchText: 'malawi +265' },
  { value: '+266', label: '🇱🇸 Lesotho (+266)', searchText: 'lesotho +266' },
  { value: '+267', label: '🇧🇼 Botswana (+267)', searchText: 'botswana +267' },
  { value: '+268', label: '🇸🇿 Eswatini (+268)', searchText: 'eswatini swaziland +268' },
  { value: '+269', label: '🇰🇲 Comoros (+269)', searchText: 'comoros +269' },
  { value: '+290', label: '🇸🇭 Saint Helena (+290)', searchText: 'saint helena +290' },
  { value: '+291', label: '🇪🇷 Eritrea (+291)', searchText: 'eritrea +291' },
  { value: '+297', label: '🇦🇼 Aruba (+297)', searchText: 'aruba +297' },
  { value: '+298', label: '🇫🇴 Faroe Islands (+298)', searchText: 'faroe islands +298' },
  { value: '+299', label: '🇬🇱 Greenland (+299)', searchText: 'greenland +299' },
  { value: '+351', label: '🇵🇹 Portugal (+351)', searchText: 'portugal +351' },
  { value: '+352', label: '🇱🇺 Luxembourg (+352)', searchText: 'luxembourg +352' },
  { value: '+353', label: '🇮🇪 Ireland (+353)', searchText: 'ireland +353' },
  { value: '+354', label: '🇮🇸 Iceland (+354)', searchText: 'iceland +354' },
  { value: '+355', label: '🇦🇱 Albania (+355)', searchText: 'albania +355' },
  { value: '+356', label: '🇲🇹 Malta (+356)', searchText: 'malta +356' },
  { value: '+357', label: '🇨🇾 Cyprus (+357)', searchText: 'cyprus +357' },
  { value: '+358', label: '🇫🇮 Finland (+358)', searchText: 'finland +358' },
  { value: '+359', label: '🇧🇬 Bulgaria (+359)', searchText: 'bulgaria +359' },
  { value: '+370', label: '🇱🇹 Lithuania (+370)', searchText: 'lithuania +370' },
  { value: '+371', label: '🇱🇻 Latvia (+371)', searchText: 'latvia +371' },
  { value: '+372', label: '🇪🇪 Estonia (+372)', searchText: 'estonia +372' },
  { value: '+373', label: '🇲🇩 Moldova (+373)', searchText: 'moldova +373' },
  { value: '+374', label: '🇦🇲 Armenia (+374)', searchText: 'armenia +374' },
  { value: '+375', label: '🇧🇾 Belarus (+375)', searchText: 'belarus +375' },
  { value: '+376', label: '🇦🇩 Andorra (+376)', searchText: 'andorra +376' },
  { value: '+377', label: '🇲🇨 Monaco (+377)', searchText: 'monaco +377' },
  { value: '+378', label: '🇸🇲 San Marino (+378)', searchText: 'san marino +378' },
  { value: '+380', label: '🇺🇦 Ukraine (+380)', searchText: 'ukraine +380' },
  { value: '+381', label: '🇷🇸 Serbia (+381)', searchText: 'serbia +381' },
  { value: '+382', label: '🇲🇪 Montenegro (+382)', searchText: 'montenegro +382' },
  { value: '+383', label: '🇽🇰 Kosovo (+383)', searchText: 'kosovo +383' },
  { value: '+385', label: '🇭🇷 Croatia (+385)', searchText: 'croatia +385' },
  { value: '+386', label: '🇸🇮 Slovenia (+386)', searchText: 'slovenia +386' },
  { value: '+387', label: '🇧🇦 Bosnia and Herzegovina (+387)', searchText: 'bosnia herzegovina +387' },
  { value: '+389', label: '🇲🇰 North Macedonia (+389)', searchText: 'north macedonia +389' },
  { value: '+420', label: '🇨🇿 Czech Republic (+420)', searchText: 'czech republic +420' },
  { value: '+421', label: '🇸🇰 Slovakia (+421)', searchText: 'slovakia +421' },
  { value: '+423', label: '🇱🇮 Liechtenstein (+423)', searchText: 'liechtenstein +423' },
  { value: '+500', label: '🇫🇰 Falkland Islands (+500)', searchText: 'falkland islands +500' },
  { value: '+501', label: '🇧🇿 Belize (+501)', searchText: 'belize +501' },
  { value: '+502', label: '🇬🇹 Guatemala (+502)', searchText: 'guatemala +502' },
  { value: '+503', label: '🇸🇻 El Salvador (+503)', searchText: 'el salvador +503' },
  { value: '+504', label: '🇭🇳 Honduras (+504)', searchText: 'honduras +504' },
  { value: '+505', label: '🇳🇮 Nicaragua (+505)', searchText: 'nicaragua +505' },
  { value: '+506', label: '🇨🇷 Costa Rica (+506)', searchText: 'costa rica +506' },
  { value: '+507', label: '🇵🇦 Panama (+507)', searchText: 'panama +507' },
  { value: '+508', label: '🇵🇲 Saint Pierre and Miquelon (+508)', searchText: 'saint pierre miquelon +508' },
  { value: '+509', label: '🇭🇹 Haiti (+509)', searchText: 'haiti +509' },
  { value: '+590', label: '🇬🇵 Guadeloupe (+590)', searchText: 'guadeloupe +590' },
  { value: '+591', label: '🇧🇴 Bolivia (+591)', searchText: 'bolivia +591' },
  { value: '+592', label: '🇬🇾 Guyana (+592)', searchText: 'guyana +592' },
  { value: '+593', label: '🇪🇨 Ecuador (+593)', searchText: 'ecuador +593' },
  { value: '+594', label: '🇬🇫 French Guiana (+594)', searchText: 'french guiana +594' },
  { value: '+595', label: '🇵🇾 Paraguay (+595)', searchText: 'paraguay +595' },
  { value: '+596', label: '🇲🇶 Martinique (+596)', searchText: 'martinique +596' },
  { value: '+597', label: '🇸🇷 Suriname (+597)', searchText: 'suriname +597' },
  { value: '+598', label: '🇺🇾 Uruguay (+598)', searchText: 'uruguay +598' },
  { value: '+599', label: '🇨🇼 Curacao (+599)', searchText: 'curacao +599' },
  { value: '+670', label: '🇹🇱 Timor-Leste (+670)', searchText: 'timor-leste east timor +670' },
  { value: '+672', label: '🇳🇫 Norfolk Island (+672)', searchText: 'norfolk island +672' },
  { value: '+673', label: '🇧🇳 Brunei (+673)', searchText: 'brunei +673' },
  { value: '+674', label: '🇳🇷 Nauru (+674)', searchText: 'nauru +674' },
  { value: '+675', label: '🇵🇬 Papua New Guinea (+675)', searchText: 'papua new guinea +675' },
  { value: '+676', label: '🇹🇴 Tonga (+676)', searchText: 'tonga +676' },
  { value: '+677', label: '🇸🇧 Solomon Islands (+677)', searchText: 'solomon islands +677' },
  { value: '+678', label: '🇻🇺 Vanuatu (+678)', searchText: 'vanuatu +678' },
  { value: '+679', label: '🇫🇯 Fiji (+679)', searchText: 'fiji +679' },
  { value: '+680', label: '🇵🇼 Palau (+680)', searchText: 'palau +680' },
  { value: '+681', label: '🇼🇫 Wallis and Futuna (+681)', searchText: 'wallis futuna +681' },
  { value: '+682', label: '🇨🇰 Cook Islands (+682)', searchText: 'cook islands +682' },
  { value: '+683', label: '🇳🇺 Niue (+683)', searchText: 'niue +683' },
  { value: '+685', label: '🇼🇸 Samoa (+685)', searchText: 'samoa +685' },
  { value: '+686', label: '🇰🇮 Kiribati (+686)', searchText: 'kiribati +686' },
  { value: '+687', label: '🇳🇨 New Caledonia (+687)', searchText: 'new caledonia +687' },
  { value: '+688', label: '🇹🇻 Tuvalu (+688)', searchText: 'tuvalu +688' },
  { value: '+689', label: '🇵🇫 French Polynesia (+689)', searchText: 'french polynesia +689' },
  { value: '+690', label: '🇹🇰 Tokelau (+690)', searchText: 'tokelau +690' },
  { value: '+691', label: '🇫🇲 Micronesia (+691)', searchText: 'micronesia +691' },
  { value: '+692', label: '🇲🇭 Marshall Islands (+692)', searchText: 'marshall islands +692' },
  { value: '+850', label: '🇰🇵 North Korea (+850)', searchText: 'north korea +850' },
  { value: '+852', label: '🇭🇰 Hong Kong (+852)', searchText: 'hong kong +852' },
  { value: '+853', label: '🇲🇴 Macau (+853)', searchText: 'macau +853' },
  { value: '+855', label: '🇰🇭 Cambodia (+855)', searchText: 'cambodia +855' },
  { value: '+856', label: '🇱🇦 Laos (+856)', searchText: 'laos +856' },
  { value: '+880', label: '🇧🇩 Bangladesh (+880)', searchText: 'bangladesh +880' },
  { value: '+886', label: '🇹🇼 Taiwan (+886)', searchText: 'taiwan +886' },
  { value: '+960', label: '🇲🇻 Maldives (+960)', searchText: 'maldives +960' },
  { value: '+961', label: '🇱🇧 Lebanon (+961)', searchText: 'lebanon +961' },
  { value: '+962', label: '🇯🇴 Jordan (+962)', searchText: 'jordan +962' },
  { value: '+963', label: '🇸🇾 Syria (+963)', searchText: 'syria +963' },
  { value: '+964', label: '🇮🇶 Iraq (+964)', searchText: 'iraq +964' },
  { value: '+965', label: '🇰🇼 Kuwait (+965)', searchText: 'kuwait +965' },
  { value: '+966', label: '🇸🇦 Saudi Arabia (+966)', searchText: 'saudi arabia +966' },
  { value: '+967', label: '🇾🇪 Yemen (+967)', searchText: 'yemen +967' },
  { value: '+968', label: '🇴🇲 Oman (+968)', searchText: 'oman +968' },
  { value: '+970', label: '🇵🇸 Palestine (+970)', searchText: 'palestine +970' },
  { value: '+971', label: '🇦🇪 United Arab Emirates (+971)', searchText: 'uae united arab emirates +971' },
  { value: '+972', label: '🇮🇱 Israel (+972)', searchText: 'israel +972' },
  { value: '+973', label: '🇧🇭 Bahrain (+973)', searchText: 'bahrain +973' },
  { value: '+974', label: '🇶🇦 Qatar (+974)', searchText: 'qatar +974' },
  { value: '+975', label: '🇧🇹 Bhutan (+975)', searchText: 'bhutan +975' },
  { value: '+976', label: '🇲🇳 Mongolia (+976)', searchText: 'mongolia +976' },
  { value: '+977', label: '🇳🇵 Nepal (+977)', searchText: 'nepal +977' },
  { value: '+992', label: '🇹🇯 Tajikistan (+992)', searchText: 'tajikistan +992' },
  { value: '+993', label: '🇹🇲 Turkmenistan (+993)', searchText: 'turkmenistan +993' },
  { value: '+994', label: '🇦🇿 Azerbaijan (+994)', searchText: 'azerbaijan +994' },
  { value: '+995', label: '🇬🇪 Georgia (+995)', searchText: 'georgia +995' },
  { value: '+996', label: '🇰🇬 Kyrgyzstan (+996)', searchText: 'kyrgyzstan +996' },
  { value: '+998', label: '🇺🇿 Uzbekistan (+998)', searchText: 'uzbekistan +998' },
]

export function normalizeDialCodeValue(value: string): string {
  if (value === '+1-ca') {
    return '+1'
  }
  return value
}

export function compactDialLabel(label: string): string {
  const flag = label.match(/^\S+/)?.[0] ?? ''
  const code = label.match(/\(\+\d+\)/)?.[0]?.replace(/[()]/g, '') ?? ''
  const compact = `${flag} ${code}`.trim()
  return compact || label
}

export function detectPreferredDialCode(): string {
  // Business default.
  return '+91'
}

export function parseCountryOptionLabel(label: string): { flag: string; countryName: string; code: string } {
  const flag = label.match(/^\S+/)?.[0] ?? ''
  const code = label.match(/\(\+\d+\)/)?.[0]?.replace(/[()]/g, '') ?? ''
  const withoutFlag = flag ? label.replace(`${flag} `, '') : label
  const countryName = withoutFlag.replace(/\s*\(\+\d+\)\s*$/, '').trim()

  return {
    flag,
    countryName,
    code,
  }
}
